######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 14 16:54:39 2010
######################################################################
QT += network
CONFIG += console
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += QHttpUploader.h
SOURCES += main.cpp QHttpUploader.cpp
